#!/usr/bin/env ruby

require 'daemons'
require 'apple_shove'
require 'pry'
# process command line arguments

args = {}
ARGV.each do |arg|
  if m = arg.match(/^--(?<key>[^=]+)=(?<val>.+)$/)
    key = m[:key].gsub('-','_').to_sym
    args[key] = m[:val]
  end
end

options = {
  stop_proc:  Proc.new { puts "Stopping daemon" },
  dir_mode:   :script
}

options[:dir] = args[:pid_dir] if args[:pid_dir]

if args[:log_dir]
  options[:log_output]  = true
  options[:log_dir]     = args[:log_dir]
end

require File.expand_path(args[:config], Dir.pwd) if args[:config]

Daemons.run_proc('apple_shove', options) do
  # max of 15 connections recommended by Apple: http://bit.ly/YNHTfE
  # note: this may be per-certificate, in which case we can crank this number
  # up much higher.
  conn_limit = args[:connection_limit] || 100

  puts "Starting daemon with a APNS connection limit of #{conn_limit}"
  puts AppleShove::CONFIG

	dmp = AppleShove::Demultiplexer.new max_apns_connections: conn_limit
  dmp.start
end
